### ISSUE TITLE
What is the right way to declare type for data object, passed to updateDoc?

### ISSUE THREAD

**Issue by ArStah** [tylim88/FirelordJS#89]
Hello, firstly, thank you for amazing library that makes everything easier!!!

I have some trouble: 

I need to implement a helper function, that makes it possible to not add some required parameters in every call of `updateDoc/batch.update`, and I'm unable to figure out, what type of `FirestoreUpdateParams.data` parameter should be to pass the typescript validation, and, more importantly, throw errors, if I'm passing wrong data to this helper function.

Here is the code: 

```typescript
import { DocumentData } from 'firebase/firestore';
import { serverTimestamp, updateDoc, DocumentReference } from 'firelordjs';

import type { WriteBatch } from 'firelordjs/dist/types';
import { ChatsMetaType } from '~/models/firestore/chat';

import store from '~/store';
import type { UpdateAction } from '~/types/global';

const autoLog = true;

const timestamp = serverTimestamp();

type FirestoreUpdateParams = {
  batch?: WriteBatch;
  ref: DocumentReference<ChatsMetaType>;
  data: __HERE__;
  action: string;
  params?: DocumentData;
  log?: boolean;
};

export function $firestoreUpdate({
  batch,
  ref,
  data,
  action,
  params = {},
  log = autoLog,
}: FirestoreUpdateParams): Promise<void> {
  const mixin = {
    update_action: {
      type: action,
      params,
      timestamp,
    } as UpdateAction,
    updated_by_uuid: store.getters['auth/user'].uid as string,
    updated_at: timestamp,
    updated_by_platform: 'web' as string,
  };

  const mixedData = {
    ...data,
    ...mixin,
  };

  if (batch) {
    if (log) {
      console.log(
        '$firestoreUpdate in batch',
        ref.path,
        action,
        params,
        mixedData,
      );
    }
    batch.update(ref, mixedData);
    return Promise.resolve();
  }

  if (log) {
    console.log('$firestoreUpdate', ref.path, action, params, mixedData);
  }
  return updateDoc(ref, mixedData);
}
```

Expecting to use it like this:

```typescript
firestoreUpdate({
  ref: ...,
  data:  {
     name: 'string', // Ok, no error, name is defined in MetaType
     name: 0,  // Error: type must be string
     unknownProp: 'value', // Error: no such property
  },
  ....
});
```

But this type would be also useful when creating data object in few places step by step

```typescript
const dataObject: __HERE__ = {};

dataObject.name = 'string'; // No error 
dataObject.name = 0; // Error, must be string
dataObject.unknownProp = 'value'; // Error, unknown prop

// ...

firestoreUpdate({
  ref: ...,
  data: dataObject,
  ....
});
```

**Comment by tylim88** [comment]
By design Firelord enforce common best practice, one of the practice is to there is no optional due to this [reason](https://github.com/tylim88/FirelordJS/discussions/86#discussioncomment-3883493)

I strongly recommend that during MetaType creation, use default value of other type

```ts
type __HERE__ = {name: string | false, age: number | false }
type ABC = MetaTypeCreator< __HERE__ , "abc">

const dataObject: __HERE__ = { name: false, age: false};
```

`false` is an ideal default value, I do not recommend `null` due to its [complicated query behavior](https://stackoverflow.com/a/71173190/5338829), there is even a setting to ban the use of null type in MetaTypeCreator (I forgot to document it, will update the doc soon, it is called `banNull`)

**Comment by tylim88** [comment]
optional is one of the highly requested features because it is very common Typescript feature

Firelord does not support optional to prevent user from accidentally cripple their query capabilities in long term

This of course make some developers feel uncomfortable

Currently I am brainstorming whether we can achieve a middle ground in V3, but that is very unlikely because Firelord aim to be the safest wrapper, I will also probably ban the use of `null` altogether in V3

**Comment by tylim88** [comment]
after giving it a deeper thought, my suggested solution does not work

I need time to patch up a solution 

meanwhile you can use `type __HERE__ = {name?: string, age?: number }` ad suppress the type error, you dont need to change the meta type

**Comment by ArStah** [comment]
Thanks for the response, but I'm not talking about optional props, all props in my MetaType are not optional, but i want to have a Type, that have one or more of those all props. Here are more parts of code to make clarify my issue:

MetaType Creation:
```typescript
type FirestoreChatData = {
  _uid: string;
  name: string;
  //
  update_action: UpdateAction;
  //
  created_at: ServerTimestamp;
  creator_uuid: string;
  created_by_platform: string;
  //
  updated_at: ServerTimestamp;
  updated_by_uuid: string;
  updated_by_platform: string;
  //
  deleted_at: ServerTimestamp | null;
  deleted_by_uuid: string | null;
  deleted_by_platform: string | null;
};

export type ChatsMetaType = MetaTypeCreator<FirestoreChatData, 'Chats'>;
``` 

Then this works
```typescript
updateDoc(ref, {
  name: 'New Name',
});
```

But this doesn't, I've expected, that Partial will do the job, but `updateDoc` doesn't accept that
```typescript
const data: Partial<ChatMetaType['write']> = {
  name: 'New Name',
};
updateDoc(ref, data)
```

About undefined props: why just not drop them when updating doc?

**Comment by tylim88** [comment]
please do `npm i firelordjs@2.2.0`

**Comment by tylim88** [comment]
you must turn on `exactOptionalPropertyTypes` in tsconfig

> About undefined props: why just not drop them when updating doc?

they are needed to explain some stuff

**Comment by ArStah** [comment]
Thanks for quick resolving!! And for exposing types too, wanted to ask about it, but forgot))
