### ISSUE TITLE
[BUG] Type instantiation is excessively deep and possibly infinite when creating MetaType

### ISSUE THREAD

**Issue by ArStah** [tylim88/FirelordJS#96]
Hey @tylim88, hope you're doing well!
I've got some weird error with the same code, that worked before and also works with `firelord` package

1. Version?
`v2.5.13`
2. What is the Meta Type?
```typescript
import type {
  MetaTypeCreator,
  Timestamp,
} from 'firelordjs'; // If use firelord instead of firelordjs - no error

export type FileData = {
  _uid: string;
  original_name: string;
  size: number;
  last_modified: Timestamp; // if comment this - no error
};

export type FirestoreDummyType = {
  _uid: string;
  avatar: FileData;
};

// ERROR: TS2589: Type instantiation is excessively deep and possibly infinite.
export type DummyMetaType = MetaTypeCreator<FirestoreDummyType, 'Dummy'>;
```
4. What operations are you trying to run?
Create MetaType with nested object, that have `Timestamp` in props
5. What do you expect?
No error should be reported. And same code works fine with `firelord` or older version of `firelordjs` (`v2.3.7` for example)
6. What do you see?
ERROR when creating MetaType: `TS2589: Type instantiation is excessively deep and possibly infinite.`

**Comment by tylim88** [comment]
what is your Typescript version and tsconfig?

I am not able to reproduce it https://codesandbox.io/s/pedantic-euler-rykiiv?file=/src/index.ts

**Comment by ArStah** [comment]
> what is your Typescript version and tsconfig?
> 
> I am not able to reproduce it https://codesandbox.io/s/pedantic-euler-rykiiv?file=/src/index.ts

You're using the wrong version of `firelordjs` in codesandbox. It seems to be broken after `2.5.0`

**Comment by tylim88** [comment]
please try version `2.5.15-beta.1`

If this is ok I will release 2.5.15

**Comment by ArStah** [comment]
Yep, it works! You're fast as always!!) Thanks!

**Comment by ArStah** [comment]
Unfortunately, it's not fixed, all the props in MetaType become `any`
<img width="457" alt="image" src="https://github.com/tylim88/FirelordJS/assets/30985699/e9b5da48-f81b-47b7-87c7-959f07ff1c07">

**Comment by tylim88** [comment]
You need to install `firebase` in codesandbox

![image](https://github.com/tylim88/FirelordJS/assets/5227509/9fe83e9d-219a-44ee-8fba-2d4c6952bf2d)

**Comment by ArStah** [comment]
That's weird, because my screenshot is from my project, where `firebase@9.22.1` is installed. I'll double check later

**Comment by tylim88** [comment]
2.5.0 will also work properly if `firebase` is installed

https://codesandbox.io/s/pedantic-euler-rykiiv?file=/src/index.ts

**Comment by tylim88** [comment]
let me know whether 2.5.0 work with firebase installed because I want to revert the change

**Comment by ArStah** [comment]
Seems that I've figured it out, something weird is happening, when using nested folder with its own `tsconfig` and `baseUrl` set to `./src`. If set `baseUrl: '.'` - it works fine with `v2.5.14`

**Comment by tylim88** [comment]
even if root directory does not have firelord and firebase installed, but you should be fine if your subdirectory has firelord and firebase installed

![image](https://github.com/tylim88/FirelordJS/assets/5227509/2c0c9e75-6f4a-4bb4-83d6-b66f8e46aba8)

![image](https://github.com/tylim88/FirelordJS/assets/5227509/41522743-6cf4-45f1-9661-840b41950f72)

**Comment by ArStah** [comment]
Yeah, that might work, but it's not my case, since the subdirectory is meant to be as an installed package without its own `node_modules`. Why: because types, generated by `firelordjs` are too big to be compiled in `.d.ts` files, so I can't build the subproject and use it as a package with proper typescript features working, so I'm using it as `git submodule` + `"subproject": "file:subproject_name"` in `package.json` so my subproject is compiled from source while running main project
